### ISSUE TITLE
Migrate conda packaging to conda forge

### ISSUE THREAD

**Issue by cmutel** [brightway-lca/brightway2#47]
# Migrating to conda forge

Conda forge offers a number of advantages (big team maintaining CI and packaging, easier installation), but the most important is it makes it much easier to build os- or arch-specific packages, which we absolutely need for MacOS ARM64 machines.

## Libraries

Here are the libraries which need to be added:

- [x] brightway2
- [x] brightway25
- [x] bw2analyzer
- [x] bw2calc  
- [x] bw2data
- [x] bw2io
- [x] bw2parameters
- [x] bw_migrations
- [x] bw_processing
- [x] constructive_geometries    
- [x] matrix_utils
- [x] mrio_common_metadata    
- [x] rower
- [x] stats_arrays
- [x] wurst 

For each library, [take the following steps](https://conda-forge.org/#add_recipe):

- Fork [conda forge staged-recipes](https://github.com/conda-forge/staged-recipes)
- Create a new branch from the staged-recipes master branch
- Adapt the [existing recipe](https://github.com/cmutel/conda-recipes) in a new "recipes/[your-package-name]" directory
- Propose the change as a pull request to the conda forge repo
- Ping the team when it builds correctly: ``@conda-forge/help-python, this is ready for review``

## Adapting the recipes

Make sure to add yourself as the maintainer, e.g. 

```yaml
extra:
  recipe-maintainers:
    - cmutel
```

Apparently the forge build is good enough that the following can be dropped:

```yaml
build:
  ignore_run_exports:
    - python_abi
```

Delete ``source: fn`` if present.

More complete ``test`` section:

```yaml
test:
  imports:
    - {{ name }}
  commands:
    - pip check
  requires:
    - pip
```

Change ``build: script`` command:

```yaml
build:
  script: {{ PYTHON }} -m pip install . -vv
```

Make Python version in build and run to be `>=3.6` if `noarch`

Fix license to be valid SPDX, e.g. `BSD-3-Clause`

Replace `setuptools` with `pip` in build section.
